- name: Provision EC2 instances
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: boot-1
        instance_type: t2.micro
        image_id: ami-04a81a99f5ec58529
        subnet_id: subnet-0af822569e9483069
        region: us-east-1
        count: "{{ item.count }}"
        wait: yes
        state: present
      loop:
        - { name: "master", instance_type: "t2.micro", count: 1 }
        - { name: "compute", instance_type: "t2.micro", count: 2 }
      register: ec2

    - name: Save EC2 instance details to inventory file
      copy:
        content: |
          [master]
          {% for instance in ec2.instances if instance.tags.Name == 'master' %}
          {{ instance.public_ip_address }}
          {% endfor %}

          [compute]
          {% for instance in ec2.instances if instance.tags.Name == 'compute' %}
          {{ instance.public_ip_address }}
          {% endfor %}
        dest: ./inventory
      when: ec2 is defined


- name: Set up HPC cluster
  hosts: all
  become: yes
  roles:
    - common
    - provisioning
    - master
    - compute













# ---
# - hosts: localhost
#   connection: local
#   gather_facts: no
#   roles:
#     - provisioning

# - hosts: master
#   become: yes
#   roles:
#     - master

# - hosts: compute
#   become: yes
#   roles:
#     - compute
# # ---
# # - hosts: localhost
# #   connection: local
# #   gather_facts: no
# #   roles:
# #     - provisioning

# # - hosts: hpc
# #   become: yes
# #   roles:
# #     - common

# # - hosts: master
# #   become: yes
# #   roles:
# #     - master

# # - hosts: compute
# #   become: yes
# #   roles:
# #     - compute
# # ---
# # - hosts: localhost
# #   connection: local
# #   gather_facts: no
# #   roles:
# #     - provisioning

# # - hosts: hpc
# #   become: yes
# #   roles:
# #     - common

# # - hosts: master
# #   become: yes
# #   roles:
# #     - master

# # - hosts: compute
# #   become: yes
# #   roles:
# #     - compute
