- name: Provision EC2 instances
  hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-east-1"
    instance_type: "t2.micro"
    ami_id: "{{ lookup('env', 'IMAGE_NAME') }}" # Replace with your desired AMI ID
    key_name: "{{ lookup('env', 'KEY_NAME') }}" # Replace with your AWS key pair name
    subnet_id: "{{ lookup('env', 'SUBNET_NAME') }}" # Replace with your subnet ID
  tasks:
    - name: Launch master node
      amazon.aws.ec2_instance:
        name: hpc-"{{ item.name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        region: "{{ aws_region }}"
        subnet_id: "{{ subnet_id }}"
        security_groups: launch-wizard-11
        count: 1
        wait: yes
      register: master_instance

    - name: Launch compute nodes
      amazon.aws.ec2_instance:
        name: hpc-"{{ item.name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        region: "{{ aws_region }}"
        subnet_id: "{{ subnet_id }}"
        security_groups: launch-wizard-11
        count: 2
        wait: yes
      register: compute_instances

    - name: Add master to inventory
      add_host:
        name: "{{ master_instance.instances[0].public_ip_address }}"
        groups: master

    - name: Add compute nodes to inventory
      add_host:
        name: "{{ item.public_ip_address }}"
        groups: compute
      loop: "{{ compute_instances.instances }}"

    - name: Save updated inventory to file
      copy:
        content: |
          [master]
          master ansible_host={{ master_instance.instances[0].public_ip_address }}

          [compute]
          {% for instance in compute_instances.instances %}
          compute{{ loop.index }} ansible_host={{ instance.public_ip_address }}
          {% endfor %}

          [all:vars]
          ansible_user=ubuntu
        dest: inventory
