- name: Create /etc/hosts file from inventory content
  copy:
    content: |
      master ansible_host={{ hostvars['master'].ansible_host }}

      {% for instance in groups['compute'] %}
      {{ instance }} ansible_host={{ hostvars[instance].ansible_host }}
      {% endfor %}

    dest: /etc/hosts


- name: Update and upgrade APT packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install common packages
  apt:
    name:
      - git
      - build-essential
      - python3-pip
      - vim
      - wget
    state: present
