- name: Install Nagios
  apt:
    name:
      - nagios4
      - nagios-nrpe-plugin
      - nagios-plugins
    state: present

- name: Start Nagios service
  service:
    name: nagios4
    state: started
    enabled: yes
