---
- name: Install Ganglia
  yum:
    name:
      - ganglia-gmond
      - ganglia-gmetad
    state: present

- name: Configure Ganglia on master
  template:
    src: gmetad.conf.j2
    dest: /etc/ganglia/gmetad.conf
  when: inventory_hostname == 'master'

- name: Configure Ganglia on compute nodes
  template:
    src: gmond.conf.j2
    dest: /etc/ganglia/gmond.conf
  when: inventory_hostname != 'master'

- name: Start and enable Ganglia services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - gmond
    - gmetad
