# - hosts: all
#   tasks:
#        - name: "Copying Installation Files"
#          copy:
#              src: "{{ item }}"
#              dest: "/root/Downloads/"
#          loop:
#              - /root/Downloads/jdk-8u171-linux-x64.rpm
#              - /root/Downloads/hadoop-1.2.1-1.x86_64.rpm
# - name: "Installing Java and Hadoop"
#          ignore_errors: yes
#          command: "rpm -i {{ item }}"
#          loop:
#              - /root/Downloads/jdk-8u171-linux-x64.rpm
#              - /root/Downloads/hadoop-1.2.1-1.x86_64.rpm --force
# - name: "Stopping firewalld service"
#          ignore_errors: yes
#          command: "systemctl stop firewalld"
# - hosts: master
#   vars_prompt:
#        - name: nndir
#          private: no
#          prompt: "Enter location directory path and name for Name Node"
# tasks:
#        - name: "Creating Name Node Directory"
#          file:
#              state: directory
#              path: "{{ nndir }}"
# - name: "Configuring hdfs-site.xml in Name Node"
#          lineinfile:
#                  path: "/etc/hadoop/hdfs-site.xml"
#                  insertafter: "<configuration>"
#                  line: "<property>
#                    \n\t <name>dfs.name.dir</name>
#                    \n\t <value>{{ nndir }}</value>
#                      \n </property>"
# - name: "Configuring core-site.xml in Name Node"
#          lineinfile:
#                  path: "/etc/hadoop/core-site.xml"
#                  insertafter: "<configuration>"
#                  line: "<property>
#                    \n\t <name>fs.default.name</name>
#                    \n\t <value>hdfs://{{ groups['namenode'][0] }}:9001</value>
#                      \n </property>"
# - name: "Formatting Name Node Directory"
#          ignore_errors: yes
#          command: "hadoop namenode -format -force"
#        - name: "Starting Name Node daemon"
#          ignore_errors: yes
#          command: "hadoop-daemon.sh start namenode"
# - hosts: compute
#   vars_prompt:
#        - name: dndir
#          private: no
#          prompt: "Enter location directory path and name for Data Node"
# tasks:
#        - name: "Creating Data Node Directory"
#          file:
#              state: directory
#              path: "{{ dndir }}"
# - name: "Configuring hdfs-site.xml in Data Node"
#          lineinfile:
#                  path: "/etc/hadoop/hdfs-site.xml"
#                  insertafter: "<configuration>"
#                  line: "<property>
#                    \n\t <name>dfs.data.dir</name>
#                    \n\t <value>{{ dndir }}</value>
#                      \n </property>"
# - name: "Configuring core-site.xml in Data Node"
#          lineinfile:
#                  path: "/etc/hadoop/core-site.xml"
#                  insertafter: "<configuration>"
#                  line: "<property>
#                    \n\t <name>fs.default.name</name>
#                    \n\t <value>hdfs://{{ groups['namenode'][0] }}:9001</value>
#                      \n </property>"
# - name: "Starting Data Node daemon"
#          ignore_errors: yes
#          command: "hadoop-daemon.sh start datanode"


---
- hosts: all
  tasks:
    - name: "Download JDK RPM"
      get_url:
        url: "https://www.oracle.com/webapps/redirect/signon?nexturl=https://download.oracle.com/otn/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-linux-x64.rpm"
        dest: "/root/Downloads/jdk-8u171-linux-x64.rpm"

    - name: "Download Hadoop RPM"
      get_url:
        url: "http://example.com/path/to/hadoop-1.2.1-1.x86_64.rpm"
        dest: "/root/Downloads/hadoop-1.2.1-1.x86_64.rpm"

    - name: "Installing Java and Hadoop"
      command: "rpm -i {{ item }}"
      loop:
        - "/root/Downloads/jdk-8u171-linux-x64.rpm"
        - "/root/Downloads/hadoop-1.2.1-1.x86_64.rpm --force"

    - name: "Stopping firewalld service"
      command: "systemctl stop firewalld"

- hosts: master
  vars_prompt:
    - name: nndir
      private: no
      prompt: "Enter location directory path and name for Name Node"

  tasks:
    - name: "Creating Name Node Directory"
      file:
        state: directory
        path: "{{ nndir }}"

    - name: "Configuring hdfs-site.xml in Name Node"
      lineinfile:
        path: "/etc/hadoop/hdfs-site.xml"
        insertafter: "<configuration>"
        line: |
          <property>
            <name>dfs.name.dir</name>
            <value>{{ nndir }}</value>
          </property>

    - name: "Configuring core-site.xml in Name Node"
      lineinfile:
        path: "/etc/hadoop/core-site.xml"
        insertafter: "<configuration>"
        line: |
          <property>
            <name>fs.default.name</name>
            <value>hdfs://{{ groups['namenode'][0] }}:9001</value>
          </property>

    - name: "Formatting Name Node Directory"
      command: "hadoop namenode -format -force"
      ignore_errors: yes

    - name: "Starting Name Node daemon"
      command: "hadoop-daemon.sh start namenode"
      ignore_errors: yes

- hosts: compute
  vars_prompt:
    - name: dndir
      private: no
      prompt: "Enter location directory path and name for Data Node"

  tasks:
    - name: "Creating Data Node Directory"
      file:
        state: directory
        path: "{{ dndir }}"

    - name: "Configuring hdfs-site.xml in Data Node"
      lineinfile:
        path: "/etc/hadoop/hdfs-site.xml"
        insertafter: "<configuration>"
        line: |
          <property>
            <name>dfs.data.dir</name>
            <value>{{ dndir }}</value>
          </property>

    - name: "Configuring core-site.xml in Data Node"
      lineinfile:
        path: "/etc/hadoop/core-site.xml"
        insertafter: "<configuration>"
        line: |
          <property>
            <name>fs.default.name</name>
            <value>hdfs://{{ groups['namenode'][0] }}:9001</value>
          </property>

    - name: "Starting Data Node daemon"
      command: "hadoop-daemon.sh start datanode"
      ignore_errors: yes
