---
- name: Setup HPC Cluster
  hosts: all
  become: yes
  roles:
    - common

- name: Configure SLURM and Ganglia
  hosts: master
  become: yes
  roles:
    - slurm
    - ganglia

- name: Configure SLURM on Compute Nodes
  hosts: compute
  become: yes
  roles:
    - slurm
