- name: Configure Munge on Manager
  hosts: master
  become: yes
  tasks:
    - name: Set permissions for Munge key on Manager
      file:
        path: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0400'

    - name: Copy Munge key to Compute nodes
      copy:
        src: /etc/munge/munge.key
        dest: /tmp/munge.key
      delegate_to: "{{ item }}"
      with_items: "{{ groups['compute'] }}"

- name: Configure Munge on Compute Nodes
  hosts: compute
  become: yes
  tasks:
    - name: Copy Munge key to /etc/munge on Compute Nodes
      copy:
        src: /tmp/munge.key
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0400'
        remote_src: yes  # Indicate that the file is located on the remote machine

    - name: Ensure Munge directories exist on Compute Nodes
      file:
        path: /etc/munge/
        state: directory
        owner: munge
        group: munge
        mode: '0700'

    - name: Enable and start Munge service
      systemd:
        name: munge
        enabled: yes
        state: started